### ISSUE TITLE
上传错误

### ISSUE THREAD

**Issue by LanXins** [jiaozitang/fileUploadDemo#5]
`nodeServer/uploads/0e1ce5d141dbc485e222626af2be5887
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'nodeServer/tmp/upload_3ed12bdb894b79381c214cc0fc4ad0d7'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'nodeServer/tmp/upload_3ed12bdb894b79381c214cc0fc4ad0d7'
}`

操作过程: 1. npm i  ->  2.npm run start  -> 3.上传文件(jpg图片) -> 4.前台显示 (校验文件进度 100% -> 上传文件进度 0% )  -> 5.后台报错
上面是报错提示, 我是 mac 电脑

**Comment by Hsing-Wei** [comment]
你要在 nodeServer 下创建 tmp 和 uploads 子目录

**Comment by LanXins** [comment]
如你所说 已经解决问题 非常感谢

**Comment by xlei1123** [comment]
这个是需要自己写nodeServer吗？
